#!/bin/bash

set -euo pipefail

now=$(date +%s)
if [ -e ~/.commitihag ]; then
   nextcheck=$(<~/.commitihag)
else
   nextcheck="$now"
fi

scriptname=$(basename "$0")
gitdir=~/.dotfiles

if [ "$nextcheck" -le "$now" ]; then
   # Check again after 7 AM tomorrow
   tomorrow=$(date -v+1d -v7H +%s)

   if [ -n "$(git -C "$gitdir" status --porcelain)" ]; then
      # Convert /home/$USER/... to ~/...
      pushd "$gitdir" > /dev/null
      gitdir_pretty=$(dirs +0)
      popd > /dev/null

      echo "$scriptname found uncommitted changes in:"
      echo "    $gitdir_pretty"
      echo "Checking again tomorrow..."
      echo
   fi

   echo "$tomorrow" > ~/.commitihag
fi
